[build]
builder = "nixpacks"

[build.nixpacks]
phases.setup = [
  "apt-get update && apt-get install -y build-essential",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
command = "gunicorn --bind 0.0.0.0:$PORT app:app" # Pastikan command ini benar dan mencakup binding ke PORT
